### ISSUE TITLE
Make first article from Jenkins

### ISSUE THREAD

**Issue by eddypapa** [Eddypapa-Szakdoga/documentation#4]
Make first article from Jenkins

* [ ]  Make template
* [ ]  Push git
* [ ]  Make some picture https://github.com/Eddypapa-Szakdoga/documentation/issues/5

Article:
* [ ] Mi a jenkins, miert jo https://github.com/Eddypapa-Szakdoga/documentation/issues/6
* [ ] Hogyan hasznalhatjuk (otthon is iparban is) https://github.com/Eddypapa-Szakdoga/documentation/issues/7
* [ ] Pelda infra bemutatasa https://github.com/Eddypapa-Szakdoga/documentation/issues/8
